version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
      - "5050:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=taskmanagement;Username=postgres;Password=postgres
    depends_on:
      - postgres
    networks:
      - taskmanagement-network

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=taskmanagement
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - taskmanagement-network

networks:
  taskmanagement-network:
    driver: bridge

volumes:
  postgres-data: